### ISSUE TITLE
Return network and HTTP errors in attested result

### ISSUE THREAD

**Issue by letmaik** [microsoft/attested-fetch#6]
Currently, any non-2xx response or network error leads to the process exiting without producing an attested result, and with the error printed to stderr. Sometimes it is useful to return those errors as part of the attested result.

To do that, I propose the following changes:
- Add `status` field to data object (following https://developer.mozilla.org/en-US/docs/Web/API/Response/status), containing the HTTP status code as number
- Instead of failing for non-2xx responses, return a result 
- For network errors, populate `status` with 0, `body` as empty string, and `certs` as empty array

**Comment by letmaik** [comment]
After more discussion we agreed on changing the data object schema a bit more:

In case of network errors, it has a single `error` field:
```json
{
  "error": {
    "message": "...error message..."
  }
}
```
If there is need in the future to expose error codes, then those would go into a new `code` field inside `error`.

If there are no network errors, then the data object is as below:

```json
{
  "result": {
    "url": "...",
    "nonce": "...",
    "status": 400,
    "body": "...",
    "certs": [...]
  }
}
```

Since this is a backwards-breaking change, the `format` identifier in the outer envelope has to change as well. 

Old: `ATTESTED_FETCH_OE_SGX_ECDSA`
New: `ATTESTED_FETCH_OE_SGX_ECDSA_V2`

**Comment by darracott** [comment]
Resolved by https://github.com/microsoft/attested-fetch/pull/7
